[package]
name = "asdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.3"
bytemuck = "1.14.3"
hassle-rs = "0.11.0"
png = "0.17.12"
